### PR TITLE
Add CLEAN_NOZZLE, Option SmartPark, EasyGet positon, upd WAIT_TEMP

### PR DESCRIPTION
**Pull request by dct-leni**

### CODE REVIEW

**Comment by pellcorp** [comment]
So I won't merge the NOZZLE_CLEAN part of this, that can't be part of the stock installation as the nozzle clean will be different depending on the mount used.

I don't understand the point of easy get position

**Comment by pellcorp** [comment]
I will add some additional comments to the PR itself

**Comment by dct-leni** [comment]
> So I won't merge the NOZZLE_CLEAN part of this, that can't be part of the stock installation as the nozzle clean will be different depending on the mount used.
> 
> I don't understand the point of easy get position

Easy get position at the end of print moves bed to lower position so it's easy to get print from bed, as by default if something small is printed it's hard to get it out as space is too small.
Moving platform down implemented in stock and Helper script.
Nozzle_clean - implemented in stock, it's default for K1 as it's has rubber pad to clean nozzle, is someone using not default mount - they may change coordinates to clean it..

**Comment by pellcorp** [comment]
> > So I won't merge the NOZZLE_CLEAN part of this, that can't be part of the stock installation as the nozzle clean will be different depending on the mount used.
> > I don't understand the point of easy get position
> 
> Easy get position at the end of print moves bed to lower position so it's easy to get print from bed, as by default if something small is printed it's hard to get it out as space is too small. Moving platform down implemented in stock and Helper script. Nozzle_clean - implemented in stock, it's default for K1 as it's has rubber pad to clean nozzle, is someone using not default mount - they may change coordinates to clean it..

So most K1s do not have a cleaning pad, this is only newer models.   Also most mounts just won't support it.  Also to get the bed to move down, you don't need a macro, you just need to change the `start_end.cfg`, `_CLIENT_VARIABLE` `variable_custom_park_dz` to something more than `3.0`.

I will not be merging the CLEAN_NOZZLE, if you want to resubmit the PR without the CLEAN_NOZZLE and without the Easy Get position, and taking into account my other comments, I will consider it, otherwise will close the PR.

**Comment by pellcorp** [comment]
> > So I won't merge the NOZZLE_CLEAN part of this, that can't be part of the stock installation as the nozzle clean will be different depending on the mount used.
> > I don't understand the point of easy get position
> 
> Easy get position at the end of print moves bed to lower position so it's easy to get print from bed, as by default if something small is printed it's hard to get it out as space is too small. Moving platform down implemented in stock and Helper script. Nozzle_clean - implemented in stock, it's default for K1 as it's has rubber pad to clean nozzle, is someone using not default mount - they may change coordinates to clean it..

Also I don't much care what helper script or stock does.   Also all of the default mounts for Simple AF will not work with the rear clean nozzle, Simple AF is not for PRtouch!

**Pull request closed without merging**
